title: Ruby on Rails 教程
keywords: Ruby on Rails, Rails, 中文, 教程, 电子书
description: Ruby on Rails 中文教程，讲解如何使用 Rails 框架开发应用，以及如何把应用部署到生产环境。
baseurl: ''
url: 'http://railstutorial-china.org'

twitter: andor_chen
repo_name: railstutorial/sample_app_4th_ed
fastspring_url: http://sites.fastspring.com/andor/product/railstutorial4th
leanpub_url: https://leanpub.com/rails-tutorial-cn
ituring_url: http://www.ituring.com.cn/book/1875
sample_url: http://uri.ac/1iVCp
coupon:

crowdfund_amount: 7785

permalink: /blog/:year/:month/:title/
exclude: ['.gitignore', 'rake', 'README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'tmp', 'package.json', 'gulpfile.js', 'node_modules', 'assets/images/railstutorial-book-banner.sketch']
keep_files: ['.git', '.gitignore', '.nojekyll']

# Converter settings
markdown: ACKramdownParser
kramdown:
  input: GFM
  auto_ids: false
  hard_wrap: false
  enable_coderay: false
  parse_block_html: true
  syntax_highlighter: rouge

sass:
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      blog_page: true
      body_class: 'single-post-page'
